# Generated by Django 4.0.3 on 2022-06-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('account_no', models.CharField(max_length=122)),
                ('ifsc_code', models.CharField(max_length=122)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=122)),
                ('source_acc_no', models.CharField(max_length=122)),
                ('Current_balance', models.IntegerField()),
                ('money_deposit', models.IntegerField()),
                ('destination_name', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
