# Generated by Django 4.0.3 on 2022-06-07 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ifsc_code',
        ),
    ]
