# Generated by Django 4.0.3 on 2022-06-07 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_customer_ifsc_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_details',
            old_name='destination_name',
            new_name='destiname',
        ),
        migrations.RenameField(
            model_name='transaction_details',
            old_name='source_acc_no',
            new_name='user_accno',
        ),
        migrations.RenameField(
            model_name='transaction_details',
            old_name='Current_balance',
            new_name='user_balance',
        ),
        migrations.RenameField(
            model_name='transaction_details',
            old_name='money_deposit',
            new_name='user_deposit',
        ),
        migrations.RenameField(
            model_name='transaction_details',
            old_name='source_name',
            new_name='user_name',
        ),
    ]
